export const EError = {
    ROUTING_ERROR:1, //  RUTA NO EXISTE
    DATABASE_ERROR:2, //ERROR EN LA BASE DE DATOS
    INVALID_JSON:3, //JSON INVALIDO EN UNA PETICION
    AUTH_ERROR:4, //ERROR DE AUTENTICACION
    INVALID_PARAM:5, //ERROR DEE PARAMETROS REFERENTES A LA RUTA
    EMPTY_FIELDS:6, //PROPIEDADES DEL PRODUCTO VACIAS AL CREARLO
    
}